image: node:18

stages:
  - build
  - deploy

#cache:
#  paths:
#    - node_modules/

#before_script:
#  - npm install

build:
  stage: build
  script:
    - rm -rf node_modules/ dist/ public/
    - npm install
    - npm run build
    - mv dist public # GitLab Pages expects files in a "public" directory
    - ls -la public # debugging
  artifacts:
    paths:
      - public
  only:
    - main # only build main branch

pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab page"
  artifacts:
    paths:
      - public
  only:
    - main # only deploy main branch
